import { TYPES } from 'tedious';

const dataTypes = {
  bit: TYPES.Bit,
  tinyint: TYPES.TinyInt,
  smallint: TYPES.SmallInt,
  int: TYPES.Int,
  bigint: TYPES.BigInt,
  numeric: TYPES.Numeric,
  decimal: TYPES.Decimal,
  smallmoney: TYPES.SmallMoney,
  money: TYPES.Money,
  float: TYPES.Float,
  real: TYPES.Real,
  smalldatetime: TYPES.SmallDateTime,
  datetime: TYPES.DateTime,
  datetime2: TYPES.DateTime2,
  datetimeoffset: TYPES.DateTimeOffset,
  time: TYPES.Time,
  date: TYPES.Date,
  char: TYPES.Char,
  varchar: TYPES.VarChar,
  text: TYPES.Text,
  nchar: TYPES.NChar,
  nvarchar: TYPES.NVarChar,
  ntext: TYPES.NText,
  binary: TYPES.Binary,
  varbinary: TYPES.VarBinary,
  image: TYPES.Image,
  null: TYPES.Null,
  TVP: TYPES.TVP,
  UDT: TYPES.UDT,
  uniqueidentifier: TYPES.UniqueIdentifier,
  variant: TYPES.Variant,
  xml: TYPES.xml,
};

export default dataTypes;
